# Generated by Django 5.2.3 on 2025-09-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Dermatologist', 'Dermatologist'), ('Orthopedic', 'Orthopedic'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Dentist', 'Dentist'), ('Gynecologist', 'Gynecologist')], max_length=20, null=True)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='doctor_profiles')),
                ('is_account_updated', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('fees', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
