# Generated by Django 5.2.3 on 2025-09-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, default='doctor_profiles/default.jpg', null=True, upload_to='doctor_profiles'),
        ),
    ]
